const products = [
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Rice",
    stock_left: 10,
    imgUrl: "/images/bag of rice.jpg",
  },
  {
    farmer: "Elvis Iyeabo",
    price: 3000,
    goods: "Bag of Beans",
    stock_left: 10,
    imgUrl: "/images/black beans.jpg",
  },
];

export default products